In [36]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot, Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [30]:
sentences = ['Movie was awesome', 'Very bad movie', 
            'Wasted my 2 hours on this movie', 
            'Ending was really bad', 'VFX wer very good', 'I need a refund', 
            'Acting was really bad', 'Script play was done well', 
            'Waiting for the next part', 'You don not want to miss this. Awesome movie!', 
            'Great movie', 'Bad direction', '3rd grade movie', 'Love the ending']
y = np.array([1,0,0,0,1,0,0,1,1,1,1,0,0,1])
vocab_size = 1000
encode = [one_hot(word, vocab_size) for word in sentences]
display(encode)

[[317, 615, 770],
 [564, 228, 317],
 [15, 886, 641, 79, 999, 265, 317],
 [694, 615, 329, 228],
 [641, 486, 564, 45],
 [612, 266, 610, 302],
 [405, 615, 329, 228],
 [830, 610, 615, 821, 192],
 [915, 785, 209, 986, 520],
 [102, 434, 786, 797, 600, 209, 265, 770, 317],
 [587, 317],
 [228, 312],
 [304, 629, 317],
 [564, 209, 694]]

In [31]:
encode_pad = pad_sequences(encode, maxlen=10, padding='pre')
print(encode_pad)

[[  0   0   0   0   0   0   0 317 615 770]
 [  0   0   0   0   0   0   0 564 228 317]
 [  0   0   0  15 886 641  79 999 265 317]
 [  0   0   0   0   0   0 694 615 329 228]
 [  0   0   0   0   0   0 641 486 564  45]
 [  0   0   0   0   0   0 612 266 610 302]
 [  0   0   0   0   0   0 405 615 329 228]
 [  0   0   0   0   0 830 610 615 821 192]
 [  0   0   0   0   0 915 785 209 986 520]
 [  0 102 434 786 797 600 209 265 770 317]
 [  0   0   0   0   0   0   0   0 587 317]
 [  0   0   0   0   0   0   0   0 228 312]
 [  0   0   0   0   0   0   0 304 629 317]
 [  0   0   0   0   0   0   0 564 209 694]]


In [32]:
model = Sequential()
model.add(Embedding(input_dim=1000, output_dim=10, input_length=10))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
display(model.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 10, 10)            10000     
                                                                 
 flatten_7 (Flatten)         (None, 100)               0         
                                                                 
 dense_7 (Dense)             (None, 1)                 101       
                                                                 
Total params: 10,101
Trainable params: 10,101
Non-trainable params: 0
_________________________________________________________________


None

In [34]:
model.fit(encode_pad, y, epochs=100, verbose=0)
loss, accuracy = model.evaluate(encode_pad, y, verbose=0)
print('Loss|Accuracy: ',(accuracy*100))

Loss|Accuracy:  100.0
